use_frameworks!

platform :ios, '9.0'

target 'LayoutDemo' do
  pod 'AnotherYogaWrapper', :path => '../AnotherYogaWrapper.podspec'
  pod 'TableViewAdaptor', :git => 'https://github.com/dengcqw/Another-UITableView-Adaptor.git'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) YOGA=1'
        end
    end
end
